// Comprehensive Quiz Data with 30+ Questions per Course
const quizDataComprehensive = {
    1: { // Web Development
        title: "Web Development Fundamentals Quiz",
        questions: [
            { id: 1, question: "What does HTML stand for?", options: ["Hyper Text Markup Language", "High Tech Modern Language", "Home Tool Markup Language", "Hyperlinks and Text Markup Language"], correct: 0, explanation: "HTML stands for Hyper Text Markup Language." },
            { id: 2, question: "Which CSS property adds space inside an element?", options: ["margin", "padding", "spacing", "gap"], correct: 1, explanation: "Padding adds space inside an element, margin adds space outside." },
            { id: 3, question: "What is the correct syntax for a JavaScript function?", options: ["function = myFunction() {}", "function myFunction() {}", "myFunction() function {}", "function: myFunction() {}"], correct: 1, explanation: "function myFunction() {} is the correct syntax." },
            { id: 4, question: "Which HTML element is used for the main heading?", options: ["<heading>", "<h1>", "<head>", "<header>"], correct: 1, explanation: "<h1> defines the most important heading." },
            { id: 5, question: "What does CSS stand for?", options: ["Computer Style Sheets", "Cascading Style Sheets", "Creative Style Sheets", "Colorful Style Sheets"], correct: 1, explanation: "CSS = Cascading Style Sheets." },
            { id: 6, question: "What is responsive web design?", options: ["Design for mobile only", "Design that adapts to different screen sizes", "Design with more colors", "Design with animations"], correct: 1, explanation: "Responsive design adapts to different devices and screen sizes." },
            { id: 7, question: "Which is a semantic HTML element?", options: ["<div>", "<span>", "<article>", "<b>"], correct: 2, explanation: "<article> is semantic, describing content structure." },
            { id: 8, question: "What does DOM stand for?", options: ["Document Object Management", "Document Object Model", "Data Object Model", "Digital Object Model"], correct: 1, explanation: "DOM = Document Object Model." },
            { id: 9, question: "How do you add a comment in CSS?", options: ["// comment", "# comment", "/* comment */", "<!-- comment -->"], correct: 2, explanation: "In CSS, comments use /* */." },
            { id: 10, question: "Which event is triggered when a user clicks an element?", options: ["onmouseover", "onclick", "onchange", "onload"], correct: 1, explanation: "onclick is triggered when user clicks." },
            { id: 11, question: "What is the z-index property used for?", options: ["Font size", "Stacking order of elements", "Color intensity", "Element opacity"], correct: 1, explanation: "z-index controls the stacking order of elements." },
            { id: 12, question: "Which is the correct HTML for a hyperlink?", options: ["<link>google.com</link>", "<a href='google.com'>Google</a>", "<url>google.com</url>", "<hyperlink>google</hyperlink>"], correct: 1, explanation: "<a> tag creates hyperlinks." },
            { id: 13, question: "What does 'px' unit represent in CSS?", options: ["Percentage", "Points", "Pixels", "Picas"], correct: 2, explanation: "px represents pixels in CSS." },
            { id: 14, question: "How do you select an element with id 'header' in CSS?", options: [".header", "#header", "header", "@header"], correct: 1, explanation: "#header selects elements with id 'header'." },
            { id: 15, question: "What is Bootstrap?", options: ["A JavaScript framework", "A CSS framework for responsive design", "A server-side language", "A database tool"], correct: 1, explanation: "Bootstrap is a popular CSS framework." },
            { id: 16, question: "Which method is used to select all elements with class 'item'?", options: ["querySelector('.item')", "getElementById('.item')", "getElementsByTag('item')", "selectClass('.item')"], correct: 0, explanation: "querySelector('.item') selects all with class 'item'." },
            { id: 17, question: "What does AJAX stand for?", options: ["Asynchronous JavaScript and XML", "Advanced JavaScript Application", "Automated JavaScript XML", "Asynchronous Java and XML"], correct: 0, explanation: "AJAX = Asynchronous JavaScript and XML." },
            { id: 18, question: "How do you center a div horizontally using flexbox?", options: ["align-items: center", "justify-content: center", "text-align: center", "margin: center"], correct: 1, explanation: "justify-content: center centers flex items horizontally." },
            { id: 19, question: "What is the purpose of the <meta> tag?", options: ["Create metadata about HTML doc", "Create large text", "Create tables", "Create lists"], correct: 0, explanation: "<meta> provides metadata about the HTML document." },
            { id: 20, question: "Which is correct to create a form?", options: ["<form></form>", "<input></input>", "<form>", "<form>"], correct: 0, explanation: "<form> tag creates forms." },
            { id: 21, question: "What is the viewport meta tag used for?", options: ["Create views", "Control layout on mobile browsers", "Show metadata", "Display ads"], correct: 1, explanation: "Viewport meta tag controls layout on mobile devices." },
            { id: 22, question: "How do you add shadow to text in CSS?", options: ["text-shadow", "shadow", "font-shadow", "text-effect"], correct: 0, explanation: "text-shadow property adds shadow to text." },
            { id: 23, question: "What is Flexbox used for?", options: ["Display fonts", "Arrange items in 1D layout", "Create 3D effects", "Manage colors"], correct: 1, explanation: "Flexbox arranges items in flexible 1D layouts." },
            { id: 24, question: "Which property makes text bold?", options: ["font-weight: bold", "text-weight: bold", "font-style: bold", "text-bold: true"], correct: 0, explanation: "font-weight: bold makes text bold." },
            { id: 25, question: "What does '===' check in JavaScript?", options: ["Equality without type check", "Equality with type check", "Greater than", "Less than"], correct: 1, explanation: "=== checks equality with type conversion." },
            { id: 26, question: "How do you add rounded corners in CSS?", options: ["border-round", "border-radius", "corner-radius", "round-corner"], correct: 1, explanation: "border-radius creates rounded corners." },
            { id: 27, question: "What is localStorage used for?", options: ["Store large files", "Store data locally in browser", "Create local variables", "Manage fonts"], correct: 1, explanation: "localStorage stores data on the browser." },
            { id: 28, question: "Which property changes text color?", options: ["background-color", "color", "font-color", "text-color"], correct: 1, explanation: "color property changes text color." },
            { id: 29, question: "What does SVG stand for?", options: ["Scalable Vector Graphics", "Server Vector Graphics", "Static Vector Graphics", "System Vector Graphics"], correct: 0, explanation: "SVG = Scalable Vector Graphics." },
            { id: 30, question: "How do you create a gradient in CSS?", options: ["gradient()", "linear-gradient()", "color-gradient()", "background-gradient()"], correct: 1, explanation: "linear-gradient() creates CSS gradients." },
            { id: 31, question: "What is the purpose of <canvas> element?", options: ["Draw graphics", "Create forms", "Display videos", "Embed audio"], correct: 0, explanation: "<canvas> is used to draw graphics with JavaScript." },
            { id: 32, question: "How do you prevent form submission?", options: ["event.stop()", "event.preventDefault()", "event.block()", "event.cancel()"], correct: 1, explanation: "event.preventDefault() prevents default form submission." }
        ]
    },
    2: { // Python Programming
        title: "Python Programming Basics Quiz",
        questions: [
            { id: 1, question: "Which symbol is used for comments in Python?", options: ["//", "#", "/*", "--"], correct: 1, explanation: "# is used for single-line comments in Python." },
            { id: 2, question: "What is the correct way to create a list?", options: ["myList = {1, 2, 3}", "myList = [1, 2, 3]", "myList = (1, 2, 3)", "myList = <1, 2, 3>"], correct: 1, explanation: "Lists use square brackets []." },
            { id: 3, question: "Which function gets the length of a list?", options: ["size()", "length()", "len()", "count()"], correct: 2, explanation: "len() returns the number of items." },
            { id: 4, question: "What is the output of 2 ** 3?", options: ["6", "5", "8", "23"], correct: 2, explanation: "** is exponentiation. 2**3 = 8." },
            { id: 5, question: "Which is a mutable data type?", options: ["String", "Tuple", "List", "Integer"], correct: 2, explanation: "Lists are mutable, strings/tuples are not." },
            { id: 6, question: "How do you create a dictionary?", options: ["dict = [key: value]", "dict = {key: value}", "dict = (key, value)", "dict = <key: value>"], correct: 1, explanation: "Dictionaries use curly braces {}." },
            { id: 7, question: "What does 'def' keyword do?", options: ["Define variables", "Define functions", "Define classes", "Define loops"], correct: 1, explanation: "def defines functions in Python." },
            { id: 8, question: "How do you import a module?", options: ["include module", "import module", "include 'module'", "load module"], correct: 1, explanation: "import keyword imports modules." },
            { id: 9, question: "What is an 'if' statement used for?", options: ["Create loops", "Make conditional decisions", "Define functions", "Create lists"], correct: 1, explanation: "if statements make conditional decisions." },
            { id: 10, question: "Which loop repeats a fixed number of times?", options: ["while", "for", "do-while", "repeat"], correct: 1, explanation: "for loop repeats a fixed number of times." },
            { id: 11, question: "What does the 'return' keyword do?", options: ["Exit a loop", "Return from a function", "Return to menu", "Return to start"], correct: 1, explanation: "return exits a function with a value." },
            { id: 12, question: "How do you handle errors in Python?", options: ["try-catch", "try-except", "error-handle", "exception-try"], correct: 1, explanation: "try-except handles errors in Python." },
            { id: 13, question: "What is a tuple?", options: ["Mutable list", "Immutable sequence", "Dictionary", "Set"], correct: 1, explanation: "Tuples are immutable sequences." },
            { id: 14, question: "How do you check if an item exists in a list?", options: ["find()", "search()", "in", "exists()"], correct: 2, explanation: "in operator checks for item existence." },
            { id: 15, question: "What does 'None' represent?", options: ["Empty", "No value/null value", "False", "Zero"], correct: 1, explanation: "None represents absence of value." },
            { id: 16, question: "How do you create a string with quotes?", options: ["string = 'hello'", "string = \"hello\"", "Both", "Neither"], correct: 2, explanation: "Both ' ' and \" \" create strings." },
            { id: 17, question: "What is list slicing?", options: ["Cutting lists", "Extracting part of list", "Sorting lists", "Merging lists"], correct: 1, explanation: "Slicing extracts a portion of a list." },
            { id: 18, question: "What does .append() do?", options: ["Remove item", "Add item to end", "Sort items", "Clear list"], correct: 1, explanation: ".append() adds item to end of list." },
            { id: 19, question: "How do you get user input?", options: ["input()", "get_input()", "read_input()", "user_input()"], correct: 0, explanation: "input() gets user input from console." },
            { id: 20, question: "What is 'self' in a class?", options: ["Global variable", "Reference to instance", "Class name", "Static variable"], correct: 1, explanation: "self refers to the instance of the class." },
            { id: 21, question: "How do you create a lambda function?", options: ["def lambda", "lambda x: x+1", "func lambda()", "lambda()"], correct: 1, explanation: "lambda x: expression creates anonymous functions." },
            { id: 22, question: "What does enumerate() do?", options: ["Count items", "Get index and value", "Remove duplicates", "Sort items"], correct: 1, explanation: "enumerate() returns index and value." },
            { id: 23, question: "How do you round a number?", options: ["round()", "truncate()", "floor()", "ceil()"], correct: 0, explanation: "round() rounds numbers." },
            { id: 24, question: "What is a decorator?", options: ["Design pattern", "Function modifier", "Class container", "Variable holder"], correct: 1, explanation: "Decorators modify function behavior." },
            { id: 25, question: "How do you convert string to integer?", options: ["str_to_int()", "int()", "to_int()", "convert_int()"], correct: 1, explanation: "int() converts to integer." },
            { id: 26, question: "What does zip() do?", options: ["Compress files", "Combine lists", "Merge dictionaries", "Sort arrays"], correct: 1, explanation: "zip() combines multiple lists." },
            { id: 27, question: "How do you iterate with keys and values?", options: ["for key in dict:", "for key, value in dict.items():", "dict.iterate()", "dict.loop()"], correct: 1, explanation: "dict.items() gets both keys and values." },
            { id: 28, question: "What is the range() function?", options: ["Get range of numbers", "Find spread of data", "Create interval", "Calculate difference"], correct: 0, explanation: "range() creates sequence of numbers." },
            { id: 29, question: "How do you remove whitespace from string?", options: ["remove_space()", ".strip()", ".trim()", ".clean()"], correct: 1, explanation: ".strip() removes leading/trailing whitespace." },
            { id: 30, question: "What does PEP 8 define?", options: ["Python syntax", "Coding style guidelines", "Library functions", "Data types"], correct: 1, explanation: "PEP 8 defines Python coding style." },
            { id: 31, question: "How do you create a set?", options: ["set = {1, 2, 3}", "set = [1, 2, 3]", "set = (1, 2, 3)", "Both A and B"], correct: 0, explanation: "Sets use curly braces without keys." },
            { id: 32, question: "What is 'args' used for?", options: ["Argument settings", "Non-keyword arguments", "Array arguments", "Argument string"], correct: 1, explanation: "*args allows variable number of arguments." }
        ]
    },
    3: { // Data Analytics
        title: "Data Analytics Fundamentals Quiz",
        questions: [
            { id: 1, question: "What does OLAP stand for?", options: ["Online Analytical Processing", "Online Application Processing", "Open Language Analytical Platform", "Operational Learning Analytics Platform"], correct: 0, explanation: "OLAP = Online Analytical Processing." },
            { id: 2, question: "Which SQL clause filters records?", options: ["FILTER", "WHERE", "SELECT", "ORDER"], correct: 1, explanation: "WHERE filters records." },
            { id: 3, question: "What is data normalization?", options: ["Increase data size", "Reduce redundancy and improve consistency", "Speed up queries", "Encrypt data"], correct: 1, explanation: "Normalization removes data redundancy." },
            { id: 4, question: "Which visualization shows data distribution?", options: ["Pie Chart", "Histogram", "Line Chart", "Bar Chart"], correct: 1, explanation: "Histograms show data distribution." },
            { id: 5, question: "What does KPI stand for?", options: ["Key Performance Indicator", "Knowledge Processing Index", "Key Profit Indicator", "Knowledge Performance Index"], correct: 0, explanation: "KPI = Key Performance Indicator." },
            { id: 6, question: "What is ETL?", options: ["Excel Transfer Language", "Extract, Transform, Load", "Electronic Text Language", "Exchange Transfer Link"], correct: 1, explanation: "ETL = Extract, Transform, Load." },
            { id: 7, question: "What is a dimension in data warehousing?", options: ["Length measurement", "Perspective of data analysis", "Data size", "Data type"], correct: 1, explanation: "Dimensions are perspectives for analysis." },
            { id: 8, question: "What is a fact table?", options: ["Contains dimensions", "Contains measures and facts", "Temporary table", "Definition table"], correct: 1, explanation: "Fact tables contain numerical measures." },
            { id: 9, question: "What is data quality?", options: ["Large datasets", "Accuracy and completeness of data", "Fast processing", "Encrypted data"], correct: 1, explanation: "Data quality means accuracy and completeness." },
            { id: 10, question: "What does SQL stand for?", options: ["Structured Query Language", "Simple Query Language", "Storage Query Language", "Standard Query Language"], correct: 0, explanation: "SQL = Structured Query Language." },
            { id: 11, question: "What is a primary key?", options: ["Main column", "Unique identifier", "Encrypted key", "Password"], correct: 1, explanation: "Primary key uniquely identifies records." },
            { id: 12, question: "What is JOIN in SQL?", options: ["Connect tables", "Combine data from tables", "Sort records", "Filter data"], correct: 1, explanation: "JOIN combines data from multiple tables." },
            { id: 13, question: "What is statistical significance?", options: ["Large numbers", "Results unlikely by chance", "Complex math", "Unusual data"], correct: 1, explanation: "Significance means results unlikely by chance." },
            { id: 14, question: "What does correlation measure?", options: ["Cause and effect", "Relationship strength between variables", "Data size", "Time duration"], correct: 1, explanation: "Correlation measures relationship strength." },
            { id: 15, question: "What is a scatter plot used for?", options: ["Single variable", "Two variable relationship", "Time series", "Categories"], correct: 1, explanation: "Scatter plots show two-variable relationships." },
            { id: 16, question: "What is a pivot table?", options: ["Rotating table", "Summarized data by categories", "Temporary table", "Main table"], correct: 1, explanation: "Pivot tables summarize data by categories." },
            { id: 17, question: "What is clustering in data analysis?", options: ["Organizing files", "Grouping similar data", "Storing data", "Deleting data"], correct: 1, explanation: "Clustering groups similar data together." },
            { id: 18, question: "What is regression analysis?", options: ["Going backward", "Predicting values from data", "Organizing data", "Counting items"], correct: 1, explanation: "Regression predicts values from data." },
            { id: 19, question: "What is an outlier?", options: ["Last item", "Unusual extreme value", "Missing value", "Incorrect format"], correct: 1, explanation: "Outliers are unusual extreme values." },
            { id: 20, question: "What is sampling?", options: ["Tasting food", "Selecting subset of data", "Copying data", "Testing software"], correct: 1, explanation: "Sampling selects subset for analysis." },
            { id: 21, question: "What is mean?", options: ["Unkind", "Average value", "Most frequent", "Range"], correct: 1, explanation: "Mean is the average value." },
            { id: 22, question: "What is median?", options: ["Middle value", "Average value", "Most frequent", "Range"], correct: 0, explanation: "Median is the middle value." },
            { id: 23, question: "What is mode?", options: ["Average", "Middle value", "Most frequent value", "Variation"], correct: 2, explanation: "Mode is most frequently occurring value." },
            { id: 24, question: "What is standard deviation?", options: ["Average value", "Measure of data spread", "Maximum value", "Minimum value"], correct: 1, explanation: "Standard deviation measures data spread." },
            { id: 25, question: "What is a contingency table?", options: ["Emergency table", "Two-way frequency table", "Temporary table", "Summary table"], correct: 1, explanation: "Contingency tables show frequency relationships." },
            { id: 26, question: "What is imputation?", options: ["Import data", "Fill missing values", "Delete data", "Compress data"], correct: 1, explanation: "Imputation fills missing values." },
            { id: 27, question: "What is feature engineering?", options: ["Car engineering", "Creating new variables", "Software development", "Building models"], correct: 1, explanation: "Feature engineering creates new variables." },
            { id: 28, question: "What is data validation?", options: ["Saving data", "Checking data accuracy", "Organizing data", "Deleting data"], correct: 1, explanation: "Validation checks data accuracy." },
            { id: 29, question: "What is a dashboard?", options: ["Vehicle part", "Visual data summary", "Database", "Data storage"], correct: 1, explanation: "Dashboards provide visual data summaries." },
            { id: 30, question: "What is business intelligence?", options: ["Smart business", "Data analysis for decisions", "Business planning", "Market research"], correct: 1, explanation: "BI uses data analysis for business decisions." }
        ]
    },
    4: { // Cloud Computing
        title: "Cloud Computing Fundamentals Quiz",
        questions: [
            { id: 1, question: "What does AWS stand for?", options: ["Amazon Web Service", "Amazon Web Services", "American Web Service", "Advanced Web Service"], correct: 1, explanation: "AWS = Amazon Web Services." },
            { id: 2, question: "What are cloud computing deployment models?", options: ["Public, Private, Hybrid", "Large, Medium, Small", "Online, Offline, Mixed", "Fast, Slow, Medium"], correct: 0, explanation: "Main models are Public, Private, Hybrid." },
            { id: 3, question: "What does IaaS stand for?", options: ["Internet as a Service", "Infrastructure as a Service", "Information as a Service", "Integration as a Service"], correct: 1, explanation: "IaaS = Infrastructure as a Service." },
            { id: 4, question: "What does PaaS stand for?", options: ["Platform as a Service", "Public as a Service", "Process as a Service", "Program as a Service"], correct: 0, explanation: "PaaS = Platform as a Service." },
            { id: 5, question: "What does SaaS stand for?", options: ["Server as a Service", "Software as a Service", "Storage as a Service", "System as a Service"], correct: 1, explanation: "SaaS = Software as a Service." },
            { id: 6, question: "What is scalability in cloud?", options: ["Size of servers", "Ability to grow resources", "Speed of processing", "Number of users"], correct: 1, explanation: "Scalability is ability to grow resources." },
            { id: 7, question: "What is Docker?", options: ["Warehouse", "Containerization platform", "Database", "Programming language"], correct: 1, explanation: "Docker is containerization platform." },
            { id: 8, question: "What is Kubernetes?", options: ["Programming language", "Container orchestration platform", "Database", "Cloud provider"], correct: 1, explanation: "Kubernetes orchestrates containers." },
            { id: 9, question: "What is an EC2 instance?", options: ["Email service", "Virtual computer in AWS", "Database", "Storage service"], correct: 1, explanation: "EC2 = Elastic Compute Cloud." },
            { id: 10, question: "What is S3 in AWS?", options: ["Server Storage Service", "Simple Storage Service", "Static Storage Service", "System Storage Service"], correct: 1, explanation: "S3 = Simple Storage Service." },
            { id: 11, question: "What is the advantage of cloud computing?", options: ["More expensive", "Less flexible", "Scalability and cost-efficiency", "Requires on-site server"], correct: 2, explanation: "Cloud offers scalability and efficiency." },
            { id: 12, question: "What is load balancing?", options: ["Weight management", "Distributing traffic across servers", "Data encryption", "Backup system"], correct: 1, explanation: "Load balancing distributes traffic." },
            { id: 13, question: "What is auto-scaling?", options: ["Manual scaling", "Automatic resource adjustment", "Database scaling", "Manual backup"], correct: 1, explanation: "Auto-scaling adjusts resources automatically." },
            { id: 14, question: "What is an API in cloud context?", options: ["Application interface for communication", "Automatic Process Interface", "Advanced Programming Instruction", "Application Process Instruction"], correct: 0, explanation: "API enables service communication." },
            { id: 15, question: "What is CDN?", options: ["Cloud Database Network", "Content Delivery Network", "Computer Data Network", "Central Distribution Network"], correct: 1, explanation: "CDN = Content Delivery Network." },
            { id: 16, question: "What is a virtual machine?", options: ["Physical computer", "Simulated computer", "Real server", "Database"], correct: 1, explanation: "VM simulates a computer." },
            { id: 17, question: "What is a container?", options: ["Box for shipping", "Lightweight application package", "Database storage", "File system"], correct: 1, explanation: "Container packages application." },
            { id: 18, question: "What is DevOps?", options: ["Developer operation only", "Development and Operations integration", "Database operations", "System development"], correct: 1, explanation: "DevOps integrates development and operations." },
            { id: 19, question: "What is CI/CD?", options: ["Continuous Integration/Continuous Deployment", "Computer Interface/Code Deployment", "Central Information/Cloud Data", "Connection/Communication Devices"], correct: 0, explanation: "CI/CD enables continuous deployment." },
            { id: 20, question: "What is containerization?", options: ["Shipping containers", "Packaging applications", "Database management", "File storage"], correct: 1, explanation: "Containerization packages applications." },
            { id: 21, question: "What is microservices?", options: ["Small servers", "Small, independent services", "Mini databases", "Tiny applications"], correct: 1, explanation: "Microservices are independent services." },
            { id: 22, question: "What is a cloud function?", options: ["Mathematical function", "Serverless code execution", "Database function", "Virtual function"], correct: 1, explanation: "Cloud functions execute code without servers." },
            { id: 23, question: "What is cloud storage?", options: ["Physical storage", "Internet-based data storage", "Local storage", "Backup only"], correct: 1, explanation: "Cloud storage stores data online." },
            { id: 24, question: "What is disaster recovery?", options: ["Recovering deleted files", "Plan for system failure recovery", "Backup only", "Encryption"], correct: 1, explanation: "Disaster recovery plans handle failures." },
            { id: 25, question: "What is high availability?", options: ["Very available", "System uptime maximization", "Quick response", "No downtime guaranteed"], correct: 1, explanation: "HA maximizes system availability." },
            { id: 26, question: "What is a subnet?", options: ["Below network", "Network subdivision", "Small network", "Network segment"], correct: 1, explanation: "Subnet divides a network." },
            { id: 27, question: "What is VPC?", options: ["Video Player Cloud", "Virtual Private Cloud", "Virtual Public Cloud", "Virtual Processing Cloud"], correct: 1, explanation: "VPC = Virtual Private Cloud." },
            { id: 28, question: "What is cloud security concern?", options: ["All good", "Data protection and compliance", "Cost only", "Speed only"], correct: 1, explanation: "Security is major cloud concern." },
            { id: 29, question: "What is multi-tenancy?", options: ["Multiple buildings", "Multiple users sharing resources", "Multiple servers", "Multiple locations"], correct: 1, explanation: "Multi-tenancy shares resources." },
            { id: 30, question: "What is cloud bursting?", options: ["Explosive growth", "Using public cloud during peaks", "Server failure", "Data loss"], correct: 1, explanation: "Bursting uses public cloud for peaks." }
        ]
    },
    5: { // Cyber Security
        title: "Cyber Security Fundamentals Quiz",
        questions: [
            { id: 1, question: "What is a firewall?", options: ["Physical wall", "Network security system", "Server", "Database"], correct: 1, explanation: "Firewall protects network traffic." },
            { id: 2, question: "What is phishing?", options: ["Fishing hobby", "Social engineering email attack", "Network protocol", "Password storage"], correct: 1, explanation: "Phishing tricks users into revealing info." },
            { id: 3, question: "What is encryption?", options: ["Data compression", "Converting data to unreadable form", "Data backup", "Data storage"], correct: 1, explanation: "Encryption secures data." },
            { id: 4, question: "What is a VPN?", options: ["Virtual Personal Network", "Virtual Private Network", "Virtual Public Network", "Virtual Processing Network"], correct: 1, explanation: "VPN = Virtual Private Network." },
            { id: 5, question: "What is malware?", options: ["Incorrect software", "Malicious software", "Old software", "Broken software"], correct: 1, explanation: "Malware damages systems." },
            { id: 6, question: "What is a virus?", options: ["Disease", "Self-replicating malicious code", "Antivirus program", "Backup file"], correct: 1, explanation: "Virus replicates and spreads." },
            { id: 7, question: "What is a worm?", options: ["Insect", "Self-propagating malware", "Security tool", "Firewall"], correct: 1, explanation: "Worms propagate without user action." },
            { id: 8, question: "What is ransomware?", options: ["Memory ransom", "Malware that locks data for payment", "Antivirus", "Backup tool"], correct: 1, explanation: "Ransomware locks data for payment." },
            { id: 9, question: "What is a trojan?", options: ["Ancient horse", "Malware disguised as legitimate", "Security software", "Encryption"], correct: 1, explanation: "Trojans hide malicious intent." },
            { id: 10, question: "What is authentication?", options: ["Authorization", "Verifying identity", "Data encryption", "Network setup"], correct: 1, explanation: "Authentication verifies identity." },
            { id: 11, question: "What is a password?", options: ["Username", "Secret code for access", "Email", "IP address"], correct: 1, explanation: "Password controls access." },
            { id: 12, question: "What is two-factor authentication?", options: ["Dual passwords", "Two verification methods", "Backup access", "Email verification"], correct: 1, explanation: "2FA uses two methods." },
            { id: 13, question: "What is SQL injection?", options: ["Database SQL", "Attacking database via SQL", "SQL query", "Database encryption"], correct: 1, explanation: "SQL injection exploits database queries." },
            { id: 14, question: "What is a DDoS attack?", options: ["Denial of Service attack", "Directory of Distributed Services", "Data Denial System", "Distributed Deletion System"], correct: 0, explanation: "DDoS overwhelms systems with traffic." },
            { id: 15, question: "What is a buffer overflow?", options: ["Memory overflow", "Writing past buffer boundary", "Storage overflow", "Cache overflow"], correct: 1, explanation: "Buffer overflow overwrites memory." },
            { id: 16, question: "What is zero-day exploit?", options: ["Day zero event", "Unknown vulnerability", "First day attack", "Zero vulnerability"], correct: 1, explanation: "Zero-day exploits unknown vulnerabilities." },
            { id: 17, question: "What is a backdoor?", options: ["Rear entrance", "Secret unauthorized access", "Main door", "Front access"], correct: 1, explanation: "Backdoor provides hidden access." },
            { id: 18, question: "What is social engineering?", options: ["Building social network", "Tricking people for info", "Social media", "Community program"], correct: 1, explanation: "Social engineering manipulates people." },
            { id: 19, question: "What is penetration testing?", options: ["Penetrating walls", "Authorized security testing", "Hacking systems", "Finding bugs"], correct: 1, explanation: "Pen testing checks security." },
            { id: 20, question: "What is a honeypot?", options: ["Actual honey container", "Fake system to trap attackers", "Security software", "Firewall"], correct: 1, explanation: "Honeypot traps attackers." },
            { id: 21, question: "What is HTTPS?", options: ["Hypertext Protocol Secure", "HTTP Secure", "Hypertext Transport Secure", "All of above"], correct: 2, explanation: "HTTPS encrypts web traffic." },
            { id: 22, question: "What is SSL/TLS?", options: ["Secure Socket Layer/Transport Layer Security", "Server Security Layer", "Software Secure Link", "System Security Link"], correct: 0, explanation: "SSL/TLS encrypts connections." },
            { id: 23, question: "What is biometric security?", options: ["Password security", "Using biological traits", "Fingerprint only", "Encryption"], correct: 1, explanation: "Biometrics use body traits." },
            { id: 24, question: "What is access control?", options: ["Computer control", "Regulating resource access", "Hardware control", "Software control"], correct: 1, explanation: "Access control restricts access." },
            { id: 25, question: "What is a security audit?", options: ["Sound audit", "Security assessment", "Financial audit", "System backup"], correct: 1, explanation: "Security audit checks defenses." },
            { id: 26, question: "What is patch management?", options: ["Clothing patches", "Applying security updates", "System patches", "Bug fixing"], correct: 1, explanation: "Patches fix security issues." },
            { id: 27, question: "What is compliance?", options: ["Obedience", "Meeting security standards", "Following rules", "Legal requirement"], correct: 1, explanation: "Compliance meets standards." },
            { id: 28, question: "What is threat modeling?", options: ["Fashion modeling", "Identifying potential threats", "Threat identification", "Security planning"], correct: 1, explanation: "Threat modeling identifies risks." },
            { id: 29, question: "What is incident response?", options: ["Quick response", "Reacting to security breach", "Emergency response", "Disaster recovery"], correct: 1, explanation: "Incident response handles breaches." },
            { id: 30, question: "What is defense in depth?", options: ["Deep defense", "Multiple security layers", "Strong firewall", "Encryption only"], correct: 1, explanation: "Defense in depth uses layers." }
        ]
    },
    6: { // UI/UX Design
        title: "UI/UX Design Fundamentals Quiz",
        questions: [
            { id: 1, question: "What does UI stand for?", options: ["User Interaction", "User Interface", "Unique Interface", "Universal Interface"], correct: 1, explanation: "UI = User Interface." },
            { id: 2, question: "What does UX stand for?", options: ["User Experience", "User Excellence", "Unique Experience", "Universal Experience"], correct: 0, explanation: "UX = User Experience." },
            { id: 3, question: "What is wireframing?", options: ["Drawing wires", "Sketching basic layout", "Writing code", "Creating colors"], correct: 1, explanation: "Wireframes show layout structure." },
            { id: 4, question: "What is a prototype?", options: ["First model", "Working model", "Design mockup", "All of above"], correct: 3, explanation: "Prototype is early working model." },
            { id: 5, question: "What is user research?", options: ["Research about users", "Studying user needs", "Finding information", "Database research"], correct: 1, explanation: "User research understands needs." },
            { id: 6, question: "What is persona?", options: ["Real person", "Fictional user character", "Brand identity", "Design style"], correct: 1, explanation: "Personas represent user types." },
            { id: 7, question: "What is usability?", options: ["Usefulness", "Ease of use", "User interface", "Design style"], correct: 1, explanation: "Usability means ease of use." },
            { id: 8, question: "What is accessibility?", options: ["Easy access", "Design for all users", "Speed", "Functionality"], correct: 1, explanation: "Accessibility serves all users." },
            { id: 9, question: "What is color theory?", options: ["Science of colors", "Color mixing principles", "Design colors", "Brand colors"], correct: 1, explanation: "Color theory guides color use." },
            { id: 10, question: "What is typography?", options: ["Text printing", "Study of typefaces", "Text alignment", "Text size"], correct: 1, explanation: "Typography is typeface design." },
            { id: 11, question: "What is responsive design?", options: ["Quick design", "Adapting to screen sizes", "Design response", "User response"], correct: 1, explanation: "Responsive adapts to devices." },
            { id: 12, question: "What is a mood board?", options: ["Happy/sad board", "Visual inspiration collection", "Design template", "Color palette"], correct: 1, explanation: "Mood boards collect inspiration." },
            { id: 13, question: "What is grid system?", options: ["System of grids", "Layout structure system", "Grid template", "Grid software"], correct: 1, explanation: "Grid systems organize layouts." },
            { id: 14, question: "What is white space?", options: ["Empty white area", "Purposeful empty space", "Background white", "Unused area"], correct: 1, explanation: "White space improves clarity." },
            { id: 15, question: "What is hierarchy?", options: ["Organization levels", "Visual emphasis order", "Content structure", "Layout order"], correct: 1, explanation: "Hierarchy guides user attention." },
            { id: 16, question: "What is consistency?", options: ["Uniform appearance", "Repeating patterns", "Design unity", "All of above"], correct: 3, explanation: "Consistency provides familiarity." },
            { id: 17, question: "What is a style guide?", options: ["Fashion guide", "Design rules document", "Website guide", "User manual"], correct: 1, explanation: "Style guides maintain consistency." },
            { id: 18, question: "What is CTA?", options: ["Click Through Action", "Call To Action", "Clickable Text Area", "Content Text Adjustment"], correct: 1, explanation: "CTA = Call To Action." },
            { id: 19, question: "What is user testing?", options: ["Testing users", "Testing with real users", "Software test", "Evaluation"], correct: 1, explanation: "User testing validates design." },
            { id: 20, question: "What is information architecture?", options: ["Building architecture", "Content organization system", "Site structure", "All of above"], correct: 2, explanation: "IA organizes information." },
            { id: 21, question: "What is navigation?", options: ["GPS navigation", "System to find content", "Menu system", "All of above"], correct: 2, explanation: "Navigation helps users move." },
            { id: 22, question: "What is a stakeholder?", options: ["People with stakes", "Project investor", "Interested party", "All of above"], correct: 3, explanation: "Stakeholders have project interest." },
            { id: 23, question: "What is a user flow?", options: ["User path", "Steps to complete task", "Task sequence", "User journey"], correct: 2, explanation: "User flow shows task steps." },
            { id: 24, question: "What is feedback loop?", options: ["Audio feedback", "User response cycle", "System response", "Error message"], correct: 1, explanation: "Feedback loop confirms actions." },
            { id: 25, question: "What is loading state?", options: ["Storage state", "Processing indication", "Data loading", "Page loading"], correct: 1, explanation: "Loading state shows progress." },
            { id: 26, question: "What is micro-interaction?", options: ["Small interaction", "Single-element interaction", "Subtle feedback", "All of above"], correct: 3, explanation: "Micro-interactions are small details." },
            { id: 27, question: "What is gamification?", options: ["Game design", "Adding game elements", "Playing games", "Game theory"], correct: 1, explanation: "Gamification adds game elements." },
            { id: 28, question: "What is A/B testing?", options: ["Testing two versions", "Version A or B", "Comparing designs", "All of above"], correct: 3, explanation: "A/B testing compares versions." },
            { id: 29, question: "What is dark mode?", options: ["Dark theme", "Low light interface", "Night mode", "All of above"], correct: 3, explanation: "Dark mode reduces eye strain." },
            { id: 30, question: "What is design thinking?", options: ["Thinking about design", "Problem-solving method", "Creative process", "All of above"], correct: 2, explanation: "Design thinking solves problems." }
        ]
    },
    7: { // Mobile Development
        title: "Mobile Development Fundamentals Quiz",
        questions: [
            { id: 1, question: "Which framework is for cross-platform development?", options: ["React Native", "Angular", "Vue.js", "Express.js"], correct: 0, explanation: "React Native builds iOS and Android apps." },
            { id: 2, question: "What is the primary iOS language?", options: ["Java", "Kotlin", "Swift", "C#"], correct: 2, explanation: "Swift is primary for iOS." },
            { id: 3, question: "Which language is native to Android?", options: ["Swift", "Kotlin", "Objective-C", "Ruby"], correct: 1, explanation: "Kotlin is official Android language." },
            { id: 4, question: "What does API stand for?", options: ["Advanced Programming Interface", "Application Programming Interface", "Application Process Integration", "Advanced Process Interface"], correct: 1, explanation: "API = Application Programming Interface." },
            { id: 5, question: "What is the most common design pattern?", options: ["MVC", "MVP", "MVVM", "All of above"], correct: 3, explanation: "All patterns used in mobile." },
            { id: 6, question: "What is React Native?", options: ["Web framework", "Mobile framework", "Native framework", "JavaScript framework"], correct: 1, explanation: "React Native builds mobile apps." },
            { id: 7, question: "What is Flutter?", options: ["Animation term", "Mobile framework", "Web framework", "Database"], correct: 1, explanation: "Flutter builds cross-platform apps." },
            { id: 8, question: "What is native development?", options: ["Original development", "Platform-specific development", "Web development", "Desktop development"], correct: 1, explanation: "Native uses platform languages." },
            { id: 9, question: "What is hybrid development?", options: ["Mixed development", "Web-based mobile apps", "Cross-platform development", "All of above"], correct: 3, explanation: "Hybrid combines web and native." },
            { id: 10, question: "What is Xcode?", options: ["Code editor", "iOS development IDE", "Android IDE", "Text editor"], correct: 1, explanation: "Xcode develops iOS apps." },
            { id: 11, question: "What is Android Studio?", options: ["Android IDE", "Code editor", "Web IDE", "Text editor"], correct: 0, explanation: "Android Studio develops Android apps." },
            { id: 12, question: "What is a permission in mobile?", options: ["Access control", "User authorization", "Feature access request", "All of above"], correct: 3, explanation: "Permissions grant feature access." },
            { id: 13, question: "What is push notification?", options: ["Manual notification", "Server-sent message", "User notification", "Alert message"], correct: 1, explanation: "Push notifications from server." },
            { id: 14, question: "What is location tracking?", options: ["GPS tracking", "User location service", "Map service", "All of above"], correct: 2, explanation: "Location tracking uses GPS." },
            { id: 15, question: "What is offline mode?", options: ["No internet mode", "Working without connection", "Sync mode", "Cache mode"], correct: 1, explanation: "Offline mode works without internet." },
            { id: 16, question: "What is UI framework?", options: ["User interface library", "Design system", "Component library", "All of above"], correct: 3, explanation: "UI frameworks provide components." },
            { id: 17, question: "What is lifecycle?", options: ["App life", "Activity states", "App state", "Process states"], correct: 1, explanation: "Lifecycle manages activity states." },
            { id: 18, question: "What is MVC pattern?", options: ["Model View Controller", "Mobile View Code", "Model View Compiler", "Main View Controller"], correct: 0, explanation: "MVC = Model View Controller." },
            { id: 19, question: "What is MVVM pattern?", options: ["Model View ViewModel", "Mobile View VModel", "Multiple View Model", "Modern View Model"], correct: 0, explanation: "MVVM = Model View ViewModel." },
            { id: 20, question: "What is state management?", options: ["Government state", "App data management", "Variable management", "Memory management"], correct: 1, explanation: "State management handles app data." },
            { id: 21, question: "What is navigation stack?", options: ["Stack structure", "Screen history", "Activity stack", "View stack"], correct: 2, explanation: "Navigation stack manages screens." },
            { id: 22, question: "What is deep linking?", options: ["Deep internet link", "Direct content link", "URL routing", "Direct app navigation"], correct: 1, explanation: "Deep links open specific content." },
            { id: 23, question: "What is battery optimization?", options: ["Battery improvement", "Reducing power use", "Battery management", "All of above"], correct: 3, explanation: "Optimization reduces battery drain." },
            { id: 24, question: "What is memory management?", options: ["RAM management", "App memory handling", "Garbage collection", "All of above"], correct: 3, explanation: "Memory management prevents leaks." },
            { id: 25, question: "What is performance optimization?", options: ["Speed improvement", "App efficiency", "Reducing lag", "All of above"], correct: 3, explanation: "Optimization improves performance." },
            { id: 26, question: "What is testing in mobile?", options: ["Software testing", "App validation", "Quality assurance", "All of above"], correct: 3, explanation: "Testing ensures app quality." },
            { id: 27, question: "What is debugging?", options: ["Finding bugs", "Fixing errors", "Error identification", "All of above"], correct: 3, explanation: "Debugging fixes code issues." },
            { id: 28, question: "What is app distribution?", options: ["App sharing", "Releasing app", "App deployment", "All of above"], correct: 3, explanation: "Distribution releases apps." },
            { id: 29, question: "What is version control?", options: ["Version management", "Code version tracking", "Git system", "All of above"], correct: 3, explanation: "Version control manages code." },
            { id: 30, question: "What is CI/CD in mobile?", options: ["Continuous Integration", "Continuous Deployment", "Automated testing", "All of above"], correct: 3, explanation: "CI/CD automates app deployment." }
        ]
    },
    8: { // Machine Learning
        title: "Machine Learning Fundamentals Quiz",
        questions: [
            { id: 1, question: "What is supervised learning goal?", options: ["Discover patterns", "Predict from labeled data", "Find clusters", "Reduce dimensions"], correct: 1, explanation: "Supervised learning predicts outcomes." },
            { id: 2, question: "Which algorithm recognizes images?", options: ["Decision Tree", "K-Means", "CNN", "Linear Regression"], correct: 2, explanation: "CNNs do image recognition." },
            { id: 3, question: "What is overfitting?", options: ["Too complex", "Poor on new data", "Too simple", "Missing features"], correct: 1, explanation: "Overfitting learns training data too well." },
            { id: 4, question: "Most popular ML library?", options: ["NumPy", "scikit-learn", "Matplotlib", "Pandas"], correct: 1, explanation: "scikit-learn is most popular." },
            { id: 5, question: "Purpose of train/test split?", options: ["Increase data", "Evaluate generalization", "Reduce time", "Remove outliers"], correct: 1, explanation: "Split evaluates model performance." },
            { id: 6, question: "What is unsupervised learning?", options: ["No teacher", "Finding patterns in unlabeled data", "Random learning", "No data"], correct: 1, explanation: "Unsupervised finds hidden patterns." },
            { id: 7, question: "What is reinforcement learning?", options: ["Learning by repetition", "Learning from rewards/penalties", "Supervised learning", "Unsupervised learning"], correct: 1, explanation: "Reinforcement uses rewards." },
            { id: 8, question: "What is clustering?", options: ["Computer clusters", "Grouping similar items", "Data storage", "Server clusters"], correct: 1, explanation: "Clustering groups similar data." },
            { id: 9, question: "What is K-Means?", options: ["K memory", "Clustering algorithm", "Kernel method", "Key metric"], correct: 1, explanation: "K-Means clusters data." },
            { id: 10, question: "What is classification?", options: ["Organizing items", "Predicting categories", "Labeling items", "Sorting data"], correct: 1, explanation: "Classification predicts categories." },
            { id: 11, question: "What is regression?", options: ["Going backward", "Predicting continuous values", "Categorizing", "Clustering"], correct: 1, explanation: "Regression predicts numbers." },
            { id: 12, question: "What is decision tree?", options: ["Real tree", "Flowchart-like model", "Graph structure", "Data structure"], correct: 1, explanation: "Decision trees classify data." },
            { id: 13, question: "What is random forest?", options: ["Random data", "Multiple decision trees", "Forest data", "Tree structure"], correct: 1, explanation: "Random forests use many trees." },
            { id: 14, question: "What is gradient boosting?", options: ["Speed optimization", "Sequential model building", "Boosting algorithm", "All of above"], correct: 3, explanation: "Gradient boosting builds models sequentially." },
            { id: 15, question: "What is neural network?", options: ["Computer network", "Brain-inspired model", "Internet network", "Connection network"], correct: 1, explanation: "Neural networks mimic brains." },
            { id: 16, question: "What is deep learning?", options: ["Deep thinking", "Many-layer neural networks", "Complex thinking", "Advanced learning"], correct: 1, explanation: "Deep learning uses many layers." },
            { id: 17, question: "What is feature scaling?", options: ["Increasing features", "Normalizing feature values", "Feature selection", "Feature engineering"], correct: 1, explanation: "Scaling normalizes values." },
            { id: 18, question: "What is feature engineering?", options: ["Creating new features", "Designing features", "Feature selection", "All of above"], correct: 0, explanation: "Feature engineering creates new variables." },
            { id: 19, question: "What is cross-validation?", options: ["Check validity", "Validating model across splits", "Data validation", "Model testing"], correct: 1, explanation: "Cross-validation tests robustness." },
            { id: 20, question: "What is regularization?", options: ["Making regular", "Preventing overfitting", "Data processing", "Model training"], correct: 1, explanation: "Regularization prevents overfitting." },
            { id: 21, question: "What is hyperparameter?", options: ["Top parameter", "Tunable model setting", "Data parameter", "Variable parameter"], correct: 1, explanation: "Hyperparameters tune models." },
            { id: 22, question: "What is confusion matrix?", options: ["Confusing matrix", "Model evaluation table", "Data matrix", "Calculation matrix"], correct: 1, explanation: "Confusion matrix evaluates classification." },
            { id: 23, question: "What is ROC curve?", options: ["Rock curve", "Performance curve", "Receiver Operating Characteristic", "Evaluation curve"], correct: 2, explanation: "ROC evaluates classifiers." },
            { id: 24, question: "What is accuracy?", options: ["Precise measurement", "Correct predictions ratio", "Model performance", "Prediction quality"], correct: 1, explanation: "Accuracy measures correctness." },
            { id: 25, question: "What is precision?", options: ["Exact measurement", "Correct positive rate", "False positive rate", "Accuracy measure"], correct: 1, explanation: "Precision: true positives / predicted positives." },
            { id: 26, question: "What is recall?", options: ["Remember", "True positive rate", "Sensitivity", "All of above"], correct: 3, explanation: "Recall: true positives / actual positives." },
            { id: 27, question: "What is F1 score?", options: ["Score formula", "Balance of precision/recall", "Performance metric", "All of above"], correct: 3, explanation: "F1 balances precision and recall." },
            { id: 28, question: "What is bias?", options: ["Prejudice", "Systematic error", "Model simplification", "All of above"], correct: 3, explanation: "Bias causes systematic errors." },
            { id: 29, question: "What is variance?", options: ["Variation", "Model sensitivity to data", "Prediction variability", "All of above"], correct: 3, explanation: "Variance: model sensitivity." },
            { id: 30, question: "What is bias-variance tradeoff?", options: ["Balance complexity", "Balancing error sources", "Model tuning", "All of above"], correct: 3, explanation: "Tradeoff balances both errors." }
        ]
    }
};

// Replace the old quizData with comprehensive version
for (let courseId in quizDataComprehensive) {
    quizData[courseId] = quizDataComprehensive[courseId];
}
